# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-25 22:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0002_auto_20190325_2130'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomePageVisit',
        ),
    ]
