# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-26 10:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homeapp', '0004_homepagevisit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='tasks_list',
        ),
        migrations.RemoveField(
            model_name='taskslist',
            name='owner',
        ),
        migrations.AddField(
            model_name='homepagevisit',
            name='who',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='TasksList',
        ),
    ]
