# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-29 01:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskslists', '0003_auto_20190327_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tasks_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_tasks', to='taskslists.TasksList'),
        ),
    ]
